### ISSUE TITLE
Support for 2024.3 edition of JetBrains IDEs

### ISSUE THREAD

**Issue by findepi** [pdet/SQLTest#11]
I installed RustRover 2024.3 and this disabled syntax highlight for .slt files.

The plugin got disabled

<img width="348" alt="image" src="https://github.com/user-attachments/assets/78f4474f-b3d9-47eb-a976-a86ae0b87b81">

This is enough a reason to downgrade backk to 2024.2.x series except that I hope update to JetBrains Java runtime may fix IDE crashes I am experiencing, so I am going to stick to this new version until it crashes too.

**Comment by pdet** [comment]
I've released a new version for the 2024.3, it will take a few days to go through the intellij approval system.

But it is also possible to download/install it manually from:  https://plugins.jetbrains.com/plugin/download?rel=true&updateId=651557

**Comment by findepi** [comment]
thank you!
