### ISSUE TITLE
Strip leading whitespace when uncommenting

### ISSUE THREAD

**Issue by findepi** [pdet/SQLTest#9]
When file contains 
```
# query I nosort
# select avg(n) as a from (VALUES (1.1), (2.2), (3.3)) as T(n)
# ----
# 2.2000000
```

and this is selected then uncomment shortcut is hit, the resulting content has leading whitespace
```
 query I nosort
 select avg(n) as a from (VALUES (1.1), (2.2), (3.3)) as T(n)
 ----
 2.2000000
```

the leading whitespace confuses some sqllogictest parsers.

**Comment by pdet** [comment]
Hey @findepi  I had a go at your issues a few minutes back and sent a new version to be published.
So the new version should support `.stl` files, work for rust, and comment adding/removing spaces.
It takes jetbrains a few days to approve these usually, but Ill ping you when I get their email. ;-)

**Comment by findepi** [comment]
@pdet wow, i am impressed. thank you so much!

**Comment by pdet** [comment]
Hi @findepi, I got the email from jetbrains so it should be up in their marketplace, could you give it a try?

**Comment by findepi** [comment]
upgraded, works like a charm, many thanks!
